version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    babel-dependencies:
      patterns:
        - "*babel*"
  ignore:
  - dependency-name: victory-native
    versions:
    - "> 32.0.2"
  # looks like it's broken and I can't debug it properly
  - dependency-name: ky
    versions:
    - "> 0.31.4"
  # following deps are managed by expo when upgrading (aka "Updated known packages to compatible versions.")
  - dependency-name: expo
    versions:
    - "*"
  - dependency-name: babel-preset-expo
    versions:
    - "*"
  - dependency-name: react
    versions:
    - "*"
  - dependency-name: react-dom
    versions:
    - "*"
  - dependency-name: react-native-screens
    versions:
    - "*"
  - dependency-name: react-native-web
    versions:
    - "*"
  - dependency-name: react-native-gesture-handler
    versions:
    - "*"
  - dependency-name: react-native-svg
    versions:
    - "*"
  - dependency-name: react-native-safe-area-context
    versions:
    - "*"
  - dependency-name: react-native-reanimated
    versions:
    - "*"
