name: Expo Publish

on:
  pull_request:
    branches:
      - master

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: yarn install
        env:
          TZ: 'Europe/Paris'
      - name: setup
        shell: bash
        env:
          PROD_HOST: ${{ secrets.PROD_HOST }}
        run: |
          cp config.js.dist config.js
          sed -i "s/my.thermo.application.com/$PROD_HOST/g" config.js
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
